name: CI

on:
  - push
  - pull_request

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

  run_examples:
    name: Cargo (Unit) Test MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: run
        uses: actions-rs/cargo@v1
        with:
          command: test

  unit_test:
    name: Cargo (Unit) Test Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: test

  e2e_test:
    name: End-to-End Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: make e2e
        run: |
          make e2e
